homepage_route: "home"
routes:
    home: "Main:home"
    register: "Main:register"
    login: "Main:login"
    logout: "Main:logout"
    article: "Article:article"
    addArticle: "Article:addArticle"
    viewArticle: "Article:viewArticle"
    deleteArticle: "Article:deleteArticle"