homepage_route: "home"
routes:
    home: "Main:home"
    register: "Main:register"
    login: "Main:login"
    logout: "Main:logout"
    article: "Article:article"
    forgottenPassword: "User:forgottenPassword"
    addArticle: "Article:addArticle"
    viewArticle: "Article:viewArticle"
    deleteArticle: "Article:deleteArticle"
    editArticle: "Article:editArticle"
    addComment: "Comment:addComment"
    editComment: "Comment:editComment"
    deleteComment: "Comment:deleteComment"
    rateArticle: "Article:rateArticle"
    rateComment: "Comment:rateComment"
    homeAdmin: "Admin:home"
    generalAdmin: "Admin:general"
    displayAdmin: "Admin:display"
    usersAdmin: "Admin:users"
    howToVegan: "Main:howToVegan"
    news : "Main:news"
    petition: "Main:petition"
    about: "Main:about"
    contactUs: "Main:contactUs"
    interview: "Main:interview"
    foodAddict: "Main:foodAddict"
    recipe: "Main:recipe"
